### ISSUE TITLE
TODO - Gjøremål fra møter

### ISSUE THREAD

**Issue by amunds1** [1-fredrikstad/sangbok#1]
Legg inn gjøremål fra møter her og kryss av når de er fullført

**Comment by amunds1** [comment]
- [ ] asddsa

**Comment by Lekesoldat** [comment]
Møtedato: 31.01.2021

- [ ] @KristofferNyvoll høre med veileder om funksjonelle/ikke-funksjonelle krav i kombinasjon med job stories.
- [ ] @kharann høre med Sanity om pricing og pitche appen.

**Comment by KristofferNyvoll** [comment]
Møtedato: 02.02.2021

- [ ] @Lekesoldat Opprette Figma-team til gruppa
- [ ] @KristofferNyvoll Finne ut av hvor vi skal dekke job stories i rapporten
- [ ] @CarlOfHoly Fikse plassering av bildet i appendix
- [ ] Alle: Skrive sine punkter i Preliminary

**Comment by amunds1** [comment]
**Før innlevering peliminary**

- [ ] Fikse hyperlenker slik at man kan klikke på "Group contract" i teksten og bli tatt til gruppekontrakten. Samme med seksjoner. Hvis refereres i 3.4.1 så tar det deg til korresponderende seksjon

**Comment by CarlOfHoly** [comment]
Møtedato: 09.02.2021

- [ ] @amunds1 @KristofferNyvoll  Se på frister for rapportskriving

**Comment by Lekesoldat** [comment]
Møtedato: 16.02.2021

- [ ] @Lekesoldat Legge inn Clockify-timer for alle etter 21:00
- [ ] @navn Beskrivelse av oppgave

**Comment by amunds1** [comment]
Møtedato: 02.03.2021

- [ ] Alle. Skrive ferdig punkt på statusrapport innen kl 17
- [ ] @KristofferNyvoll Sende mail til Bill om statusrapport og hvilke deler han skal se på på nytt

**Comment by amunds1** [comment]
- [ ] @kharann CI/CD med tabeller (2 sider)
- [ ] @Lekesoldat Sprint 1 execution (1.5 siden)
- [ ] @CarlOfHoly 
- [ ] @KristofferNyvoll 
- [ ] @amunds1 
- [ ] @Chaaarles Testing med tabell, GDPR (1 side)

Totalt tillegg i antall sider: 3.5 sider

**Comment by amunds1** [comment]
- [ ] @KristofferNyvoll Fylle inn på intro for process
- [ ] @CarlOfHoly 03-RiskAnalysis - Fjerne referanse til "Plan B" ettersom denne faller bort
- [ ] @Lekesoldat  09-VersionControl - Legge inn bilde fra GitHub Projects

**Comment by Lekesoldat** [comment]
- [ ] @Lekesoldat Sette opp slack og permanent google Meets link

**Comment by CarlOfHoly** [comment]
- [ ] @kharann Skrive en utfyllende README.md

**Comment by Lekesoldat** [comment]
# Mid term report

For å finne de relevante punktene, finn frem i PDF. Marker her når ferdig. Sidetallene er relative til PDFen.

**Page 2**
- [ ] Add what documentation you are providing  with the product.
- [ ] This can be merged with the next section to have a holistic implementation section.

**Page 5**
- [ ] Too few acronyms to have them as a separate list. You can keep it but it is still a good practice to use them in their full-form when used for the first time in the text.

**Page 8**
- [ ] Explain what is Sanity? From an external point of view, I would not know what Sanity is and therefore, I will be confused.
- [ ] what kind of influence does Sanity has over the product. Explain how it has low interest and high influence (this is something that you don't see too often).
- [ ] Usually, table captions go on top of  the table and the figure captions go under the figure.

**Page 9**
- [ ] put a screen shot of the webpage here, it will help the reader understand the text above with very little effort.

**Page 10**
- [ ] This will be more readable as a table. Or, put the legend for the figure in one line and on top of the "table" and increase the size of the table.
- [ ] The pre-study is missing. Maybe because of the nature of the project. But, the PoC can be analyzed as a pre-study.
- [ ] What does this mean, please elaborate. This is not a technical phrase, so avoid leaving such phrases without any explanations.
- [ ] Try to connect the job stories to direct customer requirements.

**Page 11**
- [ ] How did you label them?
- [ ] client's
- [ ] This sounds as if the transition to Firebase is a preference for the client. Also the whole MVP plus the expansion of functionality reads like a paradox to me. The client wants you to implement the MVP well before the deadline and then wants to transit on to firebase. Then why not adding firebase transition in the MVP itself, since it is going to take a substantial amount of time.

**Page 12**
- [ ] You don't need the bullet points here, just put the two sentences in the paragraph itself. 
- [ ] Use fullstops if you are capitalizing the first letter of each bullet point. 
- [ ] This can be part of the caption for the table, without referring to the table 1.
- [ ] Use fullstops if you are capitalizing the first letter of each bullet point. 
- [ ] I like the presentation of the architectural viewpoints with the concerns. I would suggest to streamline it a little more. You can present the view right after corresponding viewpoint. This will put less load on the readers' memory and make it easy to understand.

**Page 13**
- [ ] Capitalize the first letter of each bullet point if you are using fullstops. 
- [ ] Capitalize the first letter of each bullet point if you are using fullstops. 

**Page 14**
- [ ] Capitalize the first letter of each bullet point if you are using fullstops. 
- [ ] Capitalize the first letter of each bullet point if you are using fullstops. 

**Page 15**
- [ ] Capitalize the first letter of each bullet point if you are using fullstops. 

**Page 16**
- [ ] Which are the views? Put them in the text as well. The same goes for the organisms and molecules. Otherwise, this reads like definitions only.
- [ ] mark this in the figure as well for the completion. 
- [ ] was
- [ ] try to keep the tense consistent across the chapters. 

**Page 18**
- [ ] try to have a better resolution image here

**Page 20**
- [ ] Are there any other alternatives available, why were the ones presented in this section chosen for comparison.

**Page 21**
- [ ] Is this an advantage over Vue.js? Make it clear.
- [ ] Fjern duplikat "the"


**Page 22**
- [ ] Describe this a little more.
- [ ] Why?
- [ ] Try to make the captions of figures and tables different than the regular text. Either use centering or use italics.
- [ ] For the final version, prepare some example and show the test results. Also, is the acceptance testing not included. What you have described looks more like usability (with the final users). You also need to plan for a user acceptance testing.

**Page 23**
- [ ] In the final report, you should have the test cases, the whole test plan and scenarios and the results. 

**Page 24**
- [ ] This does not match with what you say in the reflection. "8. In our group we had 🐱 1 – Similar competencies and similar level of experience"

**Page 25**
- [ ] This seems to be an overkill and not necessary for the project.
- [ ] You have now finished two sprints but the risk matrix is not updated from the last sprint. Are there no new risks identified? Are all the older ones still valid?

**Page 28**
- [ ] Show examples.

**Page 30**
- [ ] These two are important parts of the development process, completely omitting them needs more clarification in the report. 

**Page 14**
- [ ] s

**Page 14**
- [ ] s

**Page 14**
- [ ] s

**Page 14**
- [ ] s

**Page 14**
- [ ] s

**Page 14**
- [ ] s

**Page 14**
- [ ] s

**Page 14**
- [ ] s

**Page 14**
- [ ] s

**Page 14**
- [ ] s

**Comment by CarlOfHoly** [comment]
- [ ] @CarlOfHoly Atomic Design (2.24), 3.3, 3.5, 3.6 
- [ ] @amunds1 2.5, 3.8.1, 3.8.2
- [ ] @Chaaarles 2.23 til atomic, 2.34
- [ ] @kharann 2.15, API (2.24), 2.3,
- [ ] @Lekesoldat 3.4, 3.8.3, 3.8.4
- [ ] @KristofferNyvoll 2.14, prestudy, Sanity (2.24), 2.25, 2.3.3

**Comment by Lekesoldat** [comment]
**Product reflection:**
- [ ] React.js -> Next.js, @kharann 
- [ ] Graphql -> groq, @kharann 
- [ ] Lerna -> Workspaces -> Vanlig repo, @Lekesoldat 
- [ ] Atomic Design, @CarlOfHoly 
- [ ] No test plan, @amunds1 

**Process reflection:**
- [ ]

**Comment by amunds1** [comment]
## Gjøre før levering

- Table cation må over tabeller
- Captions i kursiv
- Group i stedet for team
- Ikke presens, kun preteritum
- Alle definisjoner og fagbegrep må forklares og begrunnes, slik at en idiot som ikke kan noe fra før skjønner hva som snakkes om
- Client i stedet for customer e.l.
- Acronyms må på fatcamp

**Comment by amunds1** [comment]
# Se over andres deler

#### Gjennomgang av tekst
- [ ] Riktig tid på ord og vendinger
- [ ] Korrekt bruk av Client
- [ ] Product -> Requirements. Skriv hvordan vi lablet job stories @amunds1  
- [x] "What are the views? 2.3.5 @amunds1 
- [x] Better resolution image i package diagram (figuer 5 elns) (evt skaler ned så det ser bedre ut) @amunds1 
- [x] Oppløsning på figur 8: Ci Pipeline @amunds1 
- [ ] Risk analysis endringslogg @Lekesoldat 
- [ ] First acceptance testing meeting @Chaaarles 
- [ ] Fullføre test plan 
- [x] Unit testing @CarlOfHoly 

#### Refleksjon

**Product reflection:**
- [ ] React.js -> Next.js, @amunds1 
- [ ] Technical performance @CarlOfHoly 
- [ ] Graphql -> groq, @Lekesoldat 
- [x] Lerna -> Workspaces -> Vanlig repo, @Chaaarles 
- [x] Atomic Design, @amunds1 
- [ ] No test plan, @CarlOfHoly 

**Process reflection:**
- [x] Lean Coffee, @amunds1 
- [x] Progress and motivation graph, @Chaaarles 
- [x] Agile, @Kristoffer 
  - [x] Teamwork
  - [x] Time management
  - [x] Github Projects
  - [x] Job stories
- [ ] Communication, @kharann 
  - [ ] Client
  - [ ] Supervisor
  - [ ] Internt
  - [ ] Kommunikasjon med kommitté

## Nytt
 - [x] Sprint 5, @Chaaarles @kharann

**Comment by amunds1** [comment]
## Gjenstående oppgaver

### Ferdigstille rapport
- [ ] Skrive om brukertester
- [ ] Konklusjon
- [ ] Rette opp evt kommentarer fra Bill
- [ ] Siste finish

### Kode og annet
- [ ] Lage video
- [ ] Skrive wiki
- [ ] Skrive dokumentasjon
- [ ] Skrive ferdig testene
- [ ] Ha flere brukertester hvis det lar seg gjøre
- [ ] Fikse småting - som de to tingene doffen kommenterte sist

**Comment by amunds1** [comment]
## Product
- [ ] Intro - Existing solutions @KristofferNyvoll 
- [ ] Final product etter product reflection (produktet, hva wikien består av og fremtidig utvikling med ref til backlog) @Lekesoldat @Chaaarles @CarlOfHoly 
- [ ] 01-requirements Pri of labels @amunds1 
- [ ] 01-requirements Kodefrys og handover @amunds1 
- [ ] 02-prestudy Oppsummere valg av frontend framework @kharann 
- [ ] Existing solutions @KristofferNyvoll 
- [ ] 04-Technologies Skrive om flutter og react native så det ikke kun nevnes i tabellen og gå gjennom kommentarer @kharann 
- [ ] Test coverage @CarlOfHoly 
- [ ] Struktur av testing @amunds1 

## Process
- [ ] Endringslogg risk analysis @CarlOfHoly 

## Generelt
- [ ] Active vs passive voice @CarlOfHoly  
- [ ] Fikse tabell plassering @CarlOfHoly  
- [ ] Se etter tekst som ikke skal være der @Lekesoldat 

## Annet
- [ ] Send mail til Bill ref sprint oppsett @amunds1 @KristofferNyvoll

**Comment by Lekesoldat** [comment]
- [ ] Noen må oppdatere frontend-readme med enhetstest-script

**Comment by Lekesoldat** [comment]
- [ ] Fjerne Netlify badge fra cheat sheet

**Comment by amunds1** [comment]
### Generellt

- [ ] Fikse opp i tilbakemelding fra Magnus - @KristofferNyvoll og @amunds1 
- [ ] Skrive om sprint 6 - @KristofferNyvoll 
- [ ] Skrive veldig kort om sprint 7 - @KristofferNyvoll 
- [ ] Bytte ut mental bilde - @Chaaarles 
- [ ] Legge inn timeføring - @Lekesoldat 
- [ ] Fikse siste kodeting - @kharann 
- [ ] Handover med Doffen - @kharann @Lekesoldat  (fikser i morgen) 

### Lese gjennom rapporten og kommentere
- [ ] Begreper - @Chaaarles 
- [ ] Fokus på tid - @amunds1 
- [ ] Begrunnelse av valg - @kharann
